arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 4
trailingComma: all
plugins: ["prettier-plugin-solidity"]

overrides:
    - files: "*.sol"
      options:
          tabWidth: 4
